### ISSUE TITLE
Fork support / misskey differences

### ISSUE THREAD

**Issue by Fluffkin** [mei23/dolphin#1969]
Hi,
Sorry I don't know any Japanese.

Is this fork now the main maintained version of syuilo/dolphin? Or will the original syuilo version get updated sometime?

Also!
Is there any information on how much lighter on VPS resources Dolphin is than Misskey?  (CPU / Memory / Disk space)

Thank you

**Comment by mei23** [comment]
> Is this fork now the main maintained version of syuilo/dolphin?

I have security and major fixes, but they are not official. 

> Or will the original syuilo version get updated sometime?

I'm sorry I don't know. 

> Is there any information on how much lighter on VPS resources Dolphin is than Misskey? (CPU / Memory / Disk space)

Fewer resources are needed to build.
Also, the client probably needs less resources.
The required resources on the server side may be the same or less, but I'm not sure.

**Comment by Fluffkin** [comment]
Ok thanks.
