### ISSUE TITLE
ミュートユーザーからの通知バッジ

### ISSUE THREAD

**Issue by alter095** [mei23/dolphin#2111]
# Summary
Dolphinでは、未読の通知が来た際に通知ボタンにバッジが点灯し、通知を開くとすべてが既読になるため、バッジが消えると認識してます。
![Screenshot_20220528-101928__01__01__01__01](https://user-images.githubusercontent.com/33673048/170804603-8b6c9cf5-e46e-41fb-84d2-26e35a442242.jpg)
このバッジが、ミュートしているユーザーから通知がきた際も点灯しているようです。  
しかし、通知を開いても未読のままと判断されるのか、バッジが消えません。  
現在は該当ユーザーのミュートを一時的に解除し、通知を開くとバッジが消えます。
## Expected Behavior
ミュートしているユーザーから通知が来ても、バッジが点灯しない。  
通知を開くとバッジが消える。
## Actual Behavior
ミュートしているユーザーから通知が来ると、バッジが点灯する。  
通知を開いてもバッジが消えない。

**Comment by mei23** [comment]
初期表示時の通知表示でミュートを考慮してないバグあり。

通知を開いた時の既読処理はいちおう問題なさそう。 (ミュート分を未読でも既読扱いになる)
ただ、この処理は未読通知をさかのぼって全部取得しないと既読にはならない。
また、Streamingがたまたま切れていたりすると既読にはならない。

**Comment by alter095** [comment]
こちらでも確認したところ、Expected Behaviorの通りの動作となりました。ありがとうございました。
